### ISSUE TITLE
error: No such file or directory

### ISSUE THREAD

**Issue by JinyangLi01** [learnedsystems/SOSD#19]
Hi,
I'm trying to run your code and get this error (the dataset is fb_20M_uint64):

![image](https://user-images.githubusercontent.com/24719703/114648597-b4e76300-9d11-11eb-9039-c36dc6a9a748.png)

Could you please suggest how to solve this problem?
Thank you!

**Comment by andreaskipf** [comment]
Hi Jingyang, thanks for reaching out. The dataset is called
`fb_200M_uint64` (not `20M`). Did you try running `reproduce.sh` in the
root directory?

**Comment by niceIrene** [comment]
Hi, I had the same problem. I changed the downsample.py file to get a smaller dataset, say fb_20M_uint. When I was running the build_rmis.sh script, by using the command: "build_rmi_set fb_100M_uint64" in build_rmis.sh, it reported the same error. I looks like line15: RMI/target/release/rmi data/$DATA_NAME --param-grid ${JSON_PATH} -d rmi_data/ --threads 8 --zero-build-time is not working.

**Comment by niceIrene** [comment]
It looks like in order to run the other datasets, we need to add something to scripts/rmi_specs as you did for the other datasets?

**Comment by RyanMarcus** [comment]
In order to build RMIs for a new dataset (or a downsampled one), you'll have to generate a configuration for training the RMI on that dataset. The config files for each dataset are stored in the `scripts/rmi_specs` directory. You could try copying the RMI config for the larger dataset (i.e., `cp fb_200M_uint64.json fb_20M_uint64.json`), but this will likely produce suboptimal results.

The best way to try the smaller dataset would be to run the [RMI optimizer](https://learned.systems/rmi) to create a configuration for the smaller dataset specifically.

**Comment by niceIrene** [comment]
Thanks!
